# Generated by Django 2.2.5 on 2019-10-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='material',
            field=models.ManyToManyField(to='reserves.Material'),
        ),
    ]
