# Generated by Django 2.2.5 on 2019-10-21 13:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reserves', '0002_auto_20191016_1805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservas',
            new_name='Reserva',
        ),
    ]
